
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Wed Oct 15 21:55:56 CDT 2025
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int DIVIDE = 19;
  static final int STRING_LITERAL = 3;
  static final int INCREMENT = 43;
  static final int CHAR = 39;
  static final int CONST = 37;
  static final int MULASSIGN = 59;
  static final int GE = 25;
  static final int CHAR_LITERAL = 5;
  static final int LPAREN = 10;
  static final int CONTINUE = 34;
  static final int INT = 6;
  static final int REGISTER = 69;
  static final int DECREMENT = 44;
  static final int FOR = 31;
  static final int MINUS = 17;
  static final int TILDE = 45;
  static final int STATIC = 67;
  static final int RPAREN = 11;
  static final int OROR = 53;
  static final int NOT = 54;
  static final int SEMICOLON = 9;
  static final int AND = 26;
  static final int LT = 22;
  static final int FUN = 51;
  static final int DIVASSIGN = 60;
  static final int COMMA = 7;
  static final int BWISEXORASSIGN = 66;
  static final int LSHIFTASSIGN = 62;
  static final int ANDAND = 52;
  static final int EXTERN = 36;
  static final int PLUS = 16;
  static final int BWISEANDASSIGN = 64;
  static final int ASSIGN = 27;
  static final int IF = 28;
  static final int DOT = 56;
  static final int ID = 2;
  static final int LE = 23;
  static final int BWISEORASSIGN = 65;
  static final int EOF = 0;
  static final int RETURN = 35;
  static final int BWISEOR = 46;
  static final int error = 1;
  static final int NEQ = 21;
  static final int RSHIFTASSIGN = 63;
  static final int BREAK = 33;
  static final int MODASSIGN = 61;
  static final int VOID = 38;
  static final int EQ = 20;
  static final int SUBASSIGN = 58;
  static final int ADDASSIGN = 57;
  static final int LBRACK = 12;
  static final int TIMES = 18;
  static final int ARROW = 42;
  static final int COLON = 8;
  static final int LBRACE = 14;
  static final int ELSE = 29;
  static final int RBRACK = 13;
  static final int WHILE = 30;
  static final int RBRACE = 15;
  static final int MODULUS = 49;
  static final int BWISEXOR = 47;
  static final int DECIMAL_LITERAL = 4;
  static final int VOLATILE = 68;
  static final int QUESTION = 55;
  static final int LSHIFT = 41;
  static final int GT = 24;
  static final int VAR = 50;
  static final int BWISEAND = 48;
  static final int DO = 32;
  static final int RSHIFT = 40;

  /* non terminals */
  static final int Unmatched = 41;
  static final int bitfield_list = 23;
  static final int declaration_list = 34;
  static final int Matched = 40;
  static final int additive_expression = 6;
  static final int $START = 0;
  static final int compound_statement = 31;
  static final int argument_expression_list_opt = 20;
  static final int primary_expression = 1;
  static final int argument_expression_list = 19;
  static final int logical_or_expression = 14;
  static final int equality_expression = 9;
  static final int exclusive_or_expression = 11;
  static final int cast_expression = 4;
  static final int assignment_operator = 27;
  static final int type_augment = 33;
  static final int expression = 17;
  static final int for_initializer_declaration = 36;
  static final int unary_expression = 3;
  static final int conditional_expression = 15;
  static final int type_name = 25;
  static final int postfix_expression = 2;
  static final int logical_and_expression = 13;
  static final int shift_expression = 7;
  static final int and_expression = 10;
  static final int parameter = 30;
  static final int expression_opt = 18;
  static final int parameter_list = 29;
  static final int inclusive_or_expression = 12;
  static final int assignment_expression = 16;
  static final int type_augments = 32;
  static final int external_declaration = 38;
  static final int translation_unit = 37;
  static final int multiplicative_expression = 5;
  static final int Stmt = 39;
  static final int parameters = 28;
  static final int declaration = 21;
  static final int relational_expression = 8;
  static final int unary_operator = 26;
  static final int statement_list = 35;
  static final int bitfield = 24;
  static final int type = 22;
}

