
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Sat Oct 11 01:38:18 CDT 2025
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SHORT = 48;
  static final int SIGNED = 81;
  static final int TIMES = 18;
  static final int GT = 24;
  static final int ARROW = 65;
  static final int DIVASSIGN = 64;
  static final int CONST = 50;
  static final int GE = 25;
  static final int BWISENOT = 77;
  static final int REGISTER = 38;
  static final int ENUM = 54;
  static final int RBRACK = 13;
  static final int SIZEOF = 43;
  static final int COMMA = 7;
  static final int RBRACE = 15;
  static final int RPAREN = 11;
  static final int LBRACK = 12;
  static final int LT = 22;
  static final int ANDAND = 84;
  static final int INCREMENT = 69;
  static final int SUBASSIGN = 66;
  static final int OROR = 85;
  static final int DOUBLE = 46;
  static final int BWISEANDASSIGN = 71;
  static final int STRUCT = 41;
  static final int LBRACE = 14;
  static final int LPAREN = 10;
  static final int MODASSIGN = 72;
  static final int NOT = 86;
  static final int TILDE = 73;
  static final int LE = 23;
  static final int VAR = 36;
  static final int FLOAT = 49;
  static final int GOTO = 53;
  static final int EQ = 20;
  static final int LSHIFTASSIGN = 58;
  static final int MODULUS = 78;
  static final int LONG = 52;
  static final int PLUS = 16;
  static final int DIVIDE = 19;
  static final int QUESTION = 87;
  static final int WHILE = 31;
  static final int UNION = 47;
  static final int ASSIGN = 28;
  static final int CHAR = 55;
  static final int ADDASSIGN = 68;
  static final int SWITCH = 82;
  static final int DO = 33;
  static final int FOR = 32;
  static final int VOID = 51;
  static final int EXTERN = 45;
  static final int RETURN = 44;
  static final int ELSE = 30;
  static final int BREAK = 34;
  static final int FUN = 35;
  static final int DOT = 89;
  static final int INT = 6;
  static final int STRING_LITERAL = 3;
  static final int EOF = 0;
  static final int SEMICOLON = 9;
  static final int DEFAULT = 80;
  static final int ELIPSES = 59;
  static final int MULASSIGN = 70;
  static final int DECREMENT = 67;
  static final int MINUS = 17;
  static final int OR = 27;
  static final int error = 1;
  static final int DECIMAL_LITERAL = 4;
  static final int CONTINUE = 39;
  static final int IF = 29;
  static final int UNSIGNED = 83;
  static final int BWISEAND = 76;
  static final int BWISEOR = 74;
  static final int ID = 2;
  static final int COLON = 8;
  static final int BWISEXOR = 75;
  static final int BWISEORASSIGN = 60;
  static final int RSHIFTASSIGN = 57;
  static final int VOLATILE = 37;
  static final int CHAR_LITERAL = 5;
  static final int CASE = 79;
  static final int RSHIFT = 62;
  static final int BWISEXORASSIGN = 61;
  static final int NEQ = 21;
  static final int AND = 26;
  static final int STATIC = 42;
  static final int LSHIFT = 63;
  static final int TYPEDEF = 40;
  static final int AUTO = 56;
  static final int HASH = 88;

  /* non terminals */
  static final int declaration = 25;
  static final int primary_expression = 3;
  static final int assignment_expression = 18;
  static final int argument_expression_list_opt = 21;
  static final int Var = 2;
  static final int type = 26;
  static final int cast_expression = 6;
  static final int parameters = 29;
  static final int unary_expression = 5;
  static final int and_expression = 12;
  static final int compound_statement = 30;
  static final int conditional_expression = 17;
  static final int $START = 0;
  static final int shift_expression = 9;
  static final int initialization = 28;
  static final int postfix_expression = 4;
  static final int exclusive_or_expression = 13;
  static final int expression = 19;
  static final int type_augment = 32;
  static final int inclusive_or_expression = 14;
  static final int additive_expression = 8;
  static final int relational_expression = 10;
  static final int equality_expression = 11;
  static final int logical_and_expression = 15;
  static final int Exp = 1;
  static final int logical_or_expression = 16;
  static final int argument_expression_list = 20;
  static final int multiplicative_expression = 7;
  static final int unary_operator = 23;
  static final int type_augments = 31;
  static final int type_name = 24;
  static final int assignment_operator = 22;
  static final int bitfield_list = 27;
}

