
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Wed Oct 08 16:44:49 CDT 2025
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SHORT = 48;
  static final int SIGNED = 94;
  static final int TIMES = 18;
  static final int GT = 24;
  static final int ARROW = 65;
  static final int DIVASSIGN = 64;
  static final int CONST = 50;
  static final int BITNOT = 89;
  static final int GE = 25;
  static final int PERIOD = 76;
  static final int SEMI = 85;
  static final int REGISTER = 38;
  static final int ENUM = 54;
  static final int RBRACK = 13;
  static final int SIZEOF = 43;
  static final int COMMA = 7;
  static final int RBRACE = 15;
  static final int RPAREN = 11;
  static final int LBRACK = 12;
  static final int LT = 22;
  static final int ANDAND = 90;
  static final int INCREMENT = 69;
  static final int SUBASSIGN = 66;
  static final int OROR = 93;
  static final int DOUBLE = 46;
  static final int BWISEANDASSIGN = 71;
  static final int STRUCT = 41;
  static final int LBRACE = 14;
  static final int LPAREN = 10;
  static final int MODASSIGN = 72;
  static final int NOT = 80;
  static final int TILDE = 73;
  static final int LE = 23;
  static final int DEC = 92;
  static final int VAR = 36;
  static final int BITWISEAND = 77;
  static final int FLOAT = 49;
  static final int GOTO = 53;
  static final int EQ = 20;
  static final int LSHIFTASSIGN = 58;
  static final int MOD = 82;
  static final int MODULUS = 78;
  static final int LONG = 52;
  static final int PLUS = 16;
  static final int DIVIDE = 19;
  static final int QUESTION = 86;
  static final int WHILE = 31;
  static final int UNION = 47;
  static final int ASSIGN = 28;
  static final int CHAR = 55;
  static final int ADDASSIGN = 68;
  static final int SWITCH = 95;
  static final int DO = 33;
  static final int FOR = 32;
  static final int VOID = 51;
  static final int EXTERN = 45;
  static final int RETURN = 44;
  static final int BITOR = 88;
  static final int ELSE = 30;
  static final int BREAK = 34;
  static final int FUN = 35;
  static final int DOT = 84;
  static final int INT = 6;
  static final int STRING_LITERAL = 3;
  static final int EOF = 0;
  static final int SEMICOLON = 9;
  static final int DEFAULT = 96;
  static final int ELIPSES = 59;
  static final int MULASSIGN = 70;
  static final int DECREMENT = 67;
  static final int INC = 91;
  static final int MINUS = 17;
  static final int BITAND = 83;
  static final int OR = 27;
  static final int error = 1;
  static final int DECIMAL_LITERAL = 4;
  static final int CONTINUE = 39;
  static final int IF = 29;
  static final int UNSIGNED = 97;
  static final int BITXOR = 87;
  static final int BWISEOR = 74;
  static final int ID = 2;
  static final int COLON = 8;
  static final int BWISEXOR = 75;
  static final int BWISEORASSIGN = 60;
  static final int RSHIFTASSIGN = 57;
  static final int VOLATILE = 37;
  static final int CHAR_LITERAL = 5;
  static final int CASE = 79;
  static final int RSHIFT = 62;
  static final int BWISEXORASSIGN = 61;
  static final int NEQ = 21;
  static final int AND = 26;
  static final int STATIC = 42;
  static final int LSHIFT = 63;
  static final int TYPEDEF = 40;
  static final int AUTO = 56;
  static final int HASH = 81;

  /* non terminals */
  static final int Exp = 1;
  static final int $START = 0;
  static final int Var = 2;
}

